# Generated by Django 4.2.1 on 2023-05-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("text", models.TextField()),
                ("text_author", models.CharField(blank=True, max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("melody", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
